### ISSUE TITLE
Fenced code blocks lose language information

### ISSUE THREAD

**Issue by marionebl** [wooorm/remark-vdom#1]
**Actual**
Language information is lost for fenced code block. [Example](https://tonicdev.com/marionebl/57d31790da839a14006e2549).

```js
const remark = require('remark');
const vdom = require('remark-vdom');

const source = `
\`\`\`html
<body>
</body>
\`\`\`
`;

const opts = {
  components: {
    code(_, props) {
       const keys = Object.keys(props);
       console.log(keys.includes('className')); // => false
    }
  }
}

remark().use(vdom, opts).process(source);
```

**Expected**
[According to documentation](https://github.com/wooorm/remark-vdom#optionscomponents) fenced code blocks should yield `vdom` node with `{className: 'language-${format}'}` where `${format}` is the specified language of the fenced block.

**Comment by wooorm** [comment]
Yes, you’re right. Same goes for remark-react.

It has to do with [sanitation](https://github.com/wooorm/hast-util-sanitize), which you can read more about [here](https://github.com/wooorm/hast-util-sanitize#schema).

I’ve allowed schema’s to be turned off entirely in [remark-html](https://github.com/wooorm/remark-html/blob/master/index.js#L60), so I should really add support for it here as well 😬

**Comment by marionebl** [comment]
@wooorm Keeping around the sanitation seems like a good idea to me – if I understand correctly I'd  one has to teach the `hast-util-sanitize` to allow `className` on `code` elements? 

How would go one about that?

```js
const opts = {sanitize: merge({}, {attributes: {code: ['className']}})};
remark()
  .use(vdom, opts);
```

Apart from getting this to work to match `remark-html`, how about allowing `data-*` attributes through the sanitation?

**Comment by wooorm** [comment]
I’ve added an example of [sanitation](https://github.com/wooorm/remark-vdom#optionssanitize), which shows something much like what you suggested.

> Apart from getting this to work to match `remark-html`, how about allowing `data-*` attributes through the sanitation?

I haven’t though of that. I’m not sure if pattern matching would be the way to, or just allow `data-*` as a magic value. Thoughts?

**Comment by marionebl** [comment]
Thank you for the example, I'll give it a roll right away!

Treating `data-*` as magic value would be okay in my opinion. I don't really see other applications for full-fledged pattern matching.

**Comment by wooorm** [comment]
Done, running `npm install` should pull in the update.

Note: I went with `data*` instead of `data-*`

Cheers!

**Comment by marionebl** [comment]
Thank you!
